using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace luadec.Annotations
{
    class ESDFunctions
    {
        public class ESDFunction
        {
            public int ID;
            public string JapaneseName;
            public string EnglishEnum;

            public ESDFunction(int id, string englishEnum, string japaneseName)
            {
                ID = id;
                JapaneseName = japaneseName;
                EnglishEnum = englishEnum;
            }
        }

        public static ESDFunction[] ESDEnvs = new ESDFunction[]
        {
            new ESDFunction(0,    "IsGeneralAnimEnd",         "通常アニメ終了したか"),
            new ESDFunction(1,    "IsAttackAnimEnd",          "攻撃アニメ終了したか"),
            new ESDFunction(9,    "AnimIDOffset",             "アニメIDオフセット設定"),
            new ESDFunction(10,   "AdditiveBlendAnim",        "加算ブレンドアニメーション設定"),
            new ESDFunction(11,   "AdditiveBlendAnimOfSlot",  "スロット指定加算ブレンドアニメーション設定"),
            new ESDFunction(100,  "IsAtkRequest",             "攻撃リクエストがきたか"),
            new ESDFunction(101,  "IsAtkReleaseRequest",      "攻撃解除リクエストがきたか"),
            new ESDFunction(102,  "IsChainAtkRequest",        "連続攻撃リクエストがきたか"),
            new ESDFunction(103,  "GetAtkDuration",           "攻撃持続時間を取得"),
            new ESDFunction(104,  "GetWeaponSwitchRequest",   "㾀武器切替リクエストを取得"),
            new ESDFunction(105,  "GetCommandIDFromEvent",   "イベントからのコマンドIDを取得"),
            new ESDFunction(106,  "GetAIActionType",   "AI行動タイプを取得"),
            new ESDFunction(107,  "GetAIChainActionType",   "AI連続行動タイプを取得"),
            new ESDFunction(108,  "GetChainEvadeRequest",   "連続緊急回避リクエストがきたか"),
            new ESDFunction(109,  "GetWeaponChangeRequest",   "武器チェンジリクエストを取得"),
            new ESDFunction(110,  "GetAnimIDFromMoveParam",   "移動パラメータからアニメID取得"),
            new ESDFunction(111,  "IsThereAnyAtkRequest",   "何か攻撃リクエストがあるか"),
            new ESDFunction(112,  "IsThereAnyChainAtkRequest",   "何か連続攻撃リクエストがあるか"),
            new ESDFunction(113,  "IsItemUseMenuOpening",   "アイテム使用メニュー開くか"),
            new ESDFunction(114,  "IsMagicUseMenuOpening",   "魔法使用メニュー開くか"),
            new ESDFunction(115,  "IsItemUseMenuOpened",   "アイテム使用メニュー開いているか"),
            new ESDFunction(116,  "IsMagicUseMenuOpened",   "魔法使用メニュー開いているか"),
            new ESDFunction(117,  "GetBlendAnimIDFromMoveParam",   "移動パラメータからブレンドアニメID取得"),
            new ESDFunction(118,  "GetAIChainStepType",   "AI連続ステップタイプを取得"),
            new ESDFunction(119,  "GetTransitionToSpecialStayAnimID",   "特殊待機への遷移アニメIDを取得"),
            new ESDFunction(120,  "GetAIAtkCancelType",   "AI攻撃キャンセルタイプを取得"),
            new ESDFunction(121,  "GetWeaponCancelType",   "剣戟キャンセルタイプを取得"),
            new ESDFunction(122,  "IsWeaponCancelPossible",   "剣戟キャンセル可能か"),
            new ESDFunction(123,  "GetAIDefenseCancelType",   "AI耐えるキャンセルタイプを取得"),
            new ESDFunction(124,  "GetAIVersusBackstabCancelType",   "AI対バクスタキャンセルタイプを取得"),

            new ESDFunction(200,  "IsFalling",   "落下しているか"),
            new ESDFunction(201,  "IsLanding",   "着地しているか"),
            new ESDFunction(202,  "GetReceivedDamageType",   "食らったダメージタイプを取得"),
            new ESDFunction(203,  "IsActiveActionValid",   "能動アクション有効か"),
            new ESDFunction(204,  "GetActionEventNumber",   "アクションイベント番号取得"),
            new ESDFunction(205,  "IsNormalDmgPassThroughDuringThrow",   "投げ中に通常ダメージが通るか"),
            new ESDFunction(206,  "IsThrowing",   "投げ中か？"),
            new ESDFunction(207,  "GetWeaponSwitchState",   "武器切替状態を取得"),
            new ESDFunction(209,  "IsEquipmentSwitchPossible",   "装備切替可能な状態か"),
            new ESDFunction(210,  "IsAnimCancelPossibleInAtkRelease",   "攻撃リリースでアニメキャンセル可能か"),
            new ESDFunction(211,  "IsEmergencyStopAnimPlaying",   "緊急停止アニメ再生するか"),
            new ESDFunction(212,  "GetLockRangeState",   "ロック距離状態を取得"),
            new ESDFunction(213,  "GetLockAngleState",   "ロック角度状態を取得"),
            new ESDFunction(214,  "IsAnimCancelPossibleInDamageHit",   "ダメージヒットでアニメキャンセル可能か"),
            new ESDFunction(215,  "IsChangeToScrapeAtk",   "がりがり攻撃に変更可能か"),
            new ESDFunction(216,  "IsChangeToDeflectAtk",   "はじき攻撃に変更可能か"),
            new ESDFunction(217,  "IsChangeToAfterParrySuccess",   "パリィ成功後に変更可能か"),
            new ESDFunction(218,  "IsChangeFromNormalToBigAtk",   "通常攻撃から大攻撃に変更可能か"),
            new ESDFunction(219,  "GetMovementType",   "移動タイプ取得"),
            new ESDFunction(220,  "IsLargeAtkComboPossible",   "大攻撃でコンボ可能か"),
            new ESDFunction(221,  "IsMapActionPossible",   "マップアクション可能か"),
            new ESDFunction(222,  "GetReceivedDamageDirection",   "食らったダメージ方向を取得"),
            new ESDFunction(223,  "GetMapActionID",   "マップアクションIDを取得"),
            new ESDFunction(224,  "GetFallHeight",   "落下した高さを取得"),
            new ESDFunction(225,  "GetEquipWeaponCategory",   "装備武器カテゴリ番号取得"),
            new ESDFunction(226,  "IsHoldingBow",   "弓構え中か"),
            new ESDFunction(227,  "GetMagicAnimType",   "魔法アニメタイプ取得"),
            new ESDFunction(228,  "WasNotLargeAtk",   "大攻撃じゃなかった"),
            new ESDFunction(229,  "IsBackAtkPossible",   "背後攻撃可能か"),
            new ESDFunction(230,  "IsAfterParryAtkPossible",   "パリィ後攻撃可能か"),
            new ESDFunction(231,  "GetItemAnimType",   "アイテムアニメタイプ取得"),
            new ESDFunction(232,  "IsMagicUseable",   "魔法使用可能か"),
            new ESDFunction(233,  "IsItemUseable",   "アイテム使用可能か"),
            new ESDFunction(234,  "IsPrecisionShoot",   "精密射撃中か"),
            new ESDFunction(235,  "IsFireDamaged",   "炎ダメージ中か"),
            new ESDFunction(236,  "GetDamageLevel",   "ダメージレベル取得"),
            new ESDFunction(237,  "GetGuardLevelAction",   "ガードレベルアクション取得"),
            new ESDFunction(238,  "IsNewLeftHandAtkFromStay",   "待機からの新左手攻撃有効か"),
            new ESDFunction(239,  "IsParryFromIdle",   "待機からのパリィ攻撃有効か"),
            new ESDFunction(240,  "IsGuardFromIdle",   "待機からのガード有効か"),
            new ESDFunction(241,  "IsNewLeftHandAtkFromAtkCancel",   "攻撃キャンセルからの新左手攻撃有効か"),
            new ESDFunction(242,  "IsParryFromAtkCancel",   "攻撃キャンセルからのパリィ攻撃有効か"),
            new ESDFunction(243,  "IsGuardFromAtkCancel",   "攻撃キャンセルからのガード有効か"),
            new ESDFunction(244,  "IsTiedUp",   "金縛り中か"),
            new ESDFunction(245,  "IsOutOfAmmo",   "矢がない"),
            new ESDFunction(246,  "IsUseCatLanding",   "猫の着地有効か"),
            new ESDFunction(247,  "GetHoverMoveState",   "ホバー移動状態取得"),
            new ESDFunction(248,  "IsTruelyLanding",   "本当に着地しているか"),
            new ESDFunction(249,  "IsRightHandMagic",   "右手魔法か"),
            new ESDFunction(250,  "IsChangeToSpecialStayAnim",   "特殊待機アニメに変更するか"),
            new ESDFunction(251,  "GetSpecialStayAnimID",   "特殊待機アニメID取得"),
            new ESDFunction(252,  "AcquireSpecialDamageAnimationID",   "AcquireSpecialDamageAnimationID"),
            new ESDFunction(253,  "IsRunTurnAnimPlaying",   "走り旋回アニメ再生するか"),
            new ESDFunction(254,  "IsGenerateAction",   "ジェネレートアクションするか"),
            new ESDFunction(255,  "GetSpecialStayCancelAnimID",   "特殊待機キャンセルアニメID取得"),
            new ESDFunction(256,  "HasReceivedAnyDamage",   "少しでもダメージを食らったか"),
            new ESDFunction(257,  "GetMoveAnimParamID",   "移動アニメパラメータID取得"),
            new ESDFunction(258,  "GetGuardLevel",   "ガードレベル取得"),
            new ESDFunction(259,  "IsRequestTurnAnimStart",   "旋回アニメ開始要求があるか"),
            new ESDFunction(260,  "IsTurningWithAnim",   "アニメで旋回中か"),
            new ESDFunction(261,  "IsFlying",   "飛行中か"),
            new ESDFunction(262,  "IsAbilityInsufficient",   "能力不足か"),
            new ESDFunction(263,  "GetEquipWeightRatioForFalling",   "落下用装備重量比率取得"),
            new ESDFunction(264,  "GetFlightMotionState",   "飛行移動状態取得"),
            new ESDFunction(265,  "GetIsWeakPoint",   "弱点か取得"),
            new ESDFunction(266,  "GetMoveAnimBlendRatio",   "移動アニメブレンド率取得"),
            new ESDFunction(267,  "GetLadderActionState",   "はしごアクション状態取得"),
            new ESDFunction(268,  "IsInDisguise",   "変身中か"),
            new ESDFunction(269,  "IsCoopWait",   "協力待ちか"),
            new ESDFunction(270,  "IsCoop",   "協力か"),
            new ESDFunction(271,  "IsSpecialTransitionPossible",   "特殊遷移可能か"),
            new ESDFunction(272,  "GetLandingAnimBlendRatio",   "着地アニメブレンド率を取得"),
            new ESDFunction(273,  "GetThrowAnimID",   "投げアニメIDを取得"),
            new ESDFunction(274,  "DidOpponentDieFromThrow",   "相手が投げ死亡したか？"),
            new ESDFunction(275,  "HasThrowEnded",   "投げ抜けされたか？"),
            new ESDFunction(276,  "IsThrowSelfDeath",   "自分が投げ死亡したか？"),
            new ESDFunction(277,  "IsThrowSuccess",   "投げ抜け成功したか？"),
            new ESDFunction(278,  "GetGuardMotionCategory",   "ガードモーションカテゴリ取得"),
            new ESDFunction(279,  "IsBeingThrown",   "自分が投げられたか？"),
            new ESDFunction(280,  "IsSelfThrow",   "自分が投げたか？"),
            new ESDFunction(281,  "IsThrowDeathState",   "投げ死亡状態か？"),
            new ESDFunction(282,  "GetNewLockState",   "新ロック状態取得"),
            new ESDFunction(283,  "IsOnLadder",   "はしご中か"),
            new ESDFunction(284,  "GetPhysicalAttribute",   "物理属性を取得"),
            new ESDFunction(285,  "GetSpecialAttribute",   "特殊属性を取得"),
            new ESDFunction(286,  "GetSpecialStayDeathAnimID",   "特殊待機死亡アニメIDを取得"),
            new ESDFunction(287,  "HasReceivedAnyDamage_AnimEnd",   "少しでもダメージを食らったか_アニメ終了"),
            new ESDFunction(288,  "EggGrowth_IsHeadScratch",   "植卵_頭をかくか"),
            new ESDFunction(289,  "EggGrowth_IsBecomeEggHead",   "植卵_卵頭になるか"),
            new ESDFunction(290,  "IsStop",   "停止しているか"),
            new ESDFunction(291,  "IsSomeoneOnLadder",   "はしご上に誰かいるか"),
            new ESDFunction(292,  "IsSomeoneUnderLadder",   "はしご下に誰かいるか"),
            new ESDFunction(293,  "GetLadderHandState",   "はしごの手状態を取得"),
            new ESDFunction(294,  "DoesLadderHaveCharacters",   "はしごにキャラがいるか"),
            new ESDFunction(295,  "IsLadderRightHandStayState",   "はしごの右待機状態か"),
            new ESDFunction(296,  "IsDescendingToFloor",   "床滑り降り"),
            new ESDFunction(297,  "IsInputDirectionMatch",   "入力方向が一致するか"),
            new ESDFunction(298,  "IsSpecialTransition2Possible",   "特殊遷移２可能か"),
            new ESDFunction(299,  "IsVersusDivineDamage",   "対神聖ダメージか"),

            new ESDFunction(300,  "IsGeneralAnimCancelPossible",   "汎用アニメキャンセル可能か"),
            new ESDFunction(301,  "GetEventEzStateFlag",   "イベントEzStateフラグ取得"),
            new ESDFunction(302,  "IsLadderEventEnd",   "はしごイベント終了か"),
            new ESDFunction(303,  "IsReachBottomOfLadder",   "はしご下到着か"),
            new ESDFunction(304,  "IsReachTopOfLadder",   "はしご上到着か"),
            new ESDFunction(305,  "GetStateChangeType",   "状態変化タイプを取得"),
            new ESDFunction(306,  "IsOnLastRungOfLadder",   "はしごの最終段にいるか"),
            new ESDFunction(311,  "GetWeaponDurability",   "武器の耐久度を取得"),
            new ESDFunction(312,  "IsWeaponBroken",   "耐久度で分岐するか"),
            new ESDFunction(313,  "IsAnimEndBySkillCancel",   "技量キャンセルでアニメ終了したか"),
            new ESDFunction(314,  "EggGrowth_IsBecomeEgghead_SecondStage",   "植卵_卵頭になるか_二段目"),
            new ESDFunction(315,  "IsHamariFallDeath",   "落下ハマリで死亡させるか"),
            new ESDFunction(316,  "IsClient",   "クライアントか"),
            new ESDFunction(317,  "IsSlope",   "斜面か"),
            new ESDFunction(318,  "IsSwitchState",   "スイッチ状態か？"),
            new ESDFunction(319,  "IsPressUpKey",   "上キーを押したか？"),
            new ESDFunction(320,  "IsSpecialTurning",   "特殊旋回中か"),
            new ESDFunction(321,  "GetIntValueForTest",   "テスト用Int値取得"),
            new ESDFunction(322,  "IsObjActInterpolatedMotion",   "ObjActによる移動補間中か"),
            new ESDFunction(323,  "GetObjActTargetDirection",   "ObjActのターゲット方向取得"),
            new ESDFunction(324,  "GetObjActRemainingInterpolateTime",   "ObjAct残り補間時間取得"),
            new ESDFunction(325,  "IsGap",   "隙か"),
            new ESDFunction(326,  "GetWeaponID",   "剣戟Id取得"),
            new ESDFunction(327,  "IsMovingLaterally",   "平行移動中か"),
            new ESDFunction(328,  "IsNet",   "ネットか"),
            new ESDFunction(329,  "HasBrokenSA",   "SAブレイクしたか"),
            new ESDFunction(330,  "IsEmergencyQuickTurnActivated",   "緊急時クイックターン発動許可中か"),
            new ESDFunction(331,  "IsDoubleChantPossible",   "二重詠唱可能か"),
            new ESDFunction(332,  "IsAnimOver",   "アニメが終了したか"),
            new ESDFunction(333,  "ObtainedDT",   "DT取得"),
            new ESDFunction(334,  "GetBehaviorID",   "Behavior用識別値取得"),
            new ESDFunction(335,  "IsTwoHandPossible",   "両手持ち可能か"),
            new ESDFunction(336,  "IsPartDamageAdditiveBlendInvalid",   "部位・ダメージ加算ブレンド無効か"),
            new ESDFunction(337,  "IsThrowPosRealign",   "投げ位置合わせ中か"),
            new ESDFunction(338,  "GetBoltLoadingState",   "ボルト装填状態取得"),
            new ESDFunction(339,  "IsAnimEnd",   "アニメ終了か"),
            new ESDFunction(340,  "IsTwinSwords",   "双剣か"),
            new ESDFunction(341,  "GetTurnAngleForDelayedTurn",   "遅延旋回用TurnAngle取得"),
            new ESDFunction(342,  "GetThrowDefenseCount",   "投げ抜け抵抗回数取得"),
            new ESDFunction(343,  "IsEmergencyEvasionPossible",   "緊急回避可能か"),
            new ESDFunction(344,  "HasEnoughArtsPoints",   "アーツポイント足りるか"),
            new ESDFunction(345,  "GetEquipWeaponSpecialCategoryNumber",   "装備武器特殊カテゴリ番号取得"),
            new ESDFunction(346,  "CheckForEventAnimPlaybackRequest",   "イベントアニメ再生要求があるか"),
            new ESDFunction(347,  "IsFemale",   "女性か"),
            new ESDFunction(348,  "GetDelayTurnAngleDifference",   "遅延旋回角度差取得"),
            new ESDFunction(349,  "IsDamageMotionOff",   "ダメージモーション無効か"),
            new ESDFunction(350,  "HasReachedStatsNeededForWeapon",   "武器能力開放ステータス値到達か"),
            new ESDFunction(351,  "UpperArmControlOuterAngle",   "上腕制御外側角度"),
            new ESDFunction(352,  "UpperArmControlTopAndBottomAngle",   "上腕制御上下角度"),
            new ESDFunction(353,  "CompleteLadderSlideDown",   "はしご滑り降り完了"),
            new ESDFunction(354,  "GetLadderRungCount",   "はしご段数取得"),
            new ESDFunction(355,  "GetNumberOfRungsBelowOnLadder",   "滑り降り停止先のはしご段数取得"),
            new ESDFunction(356,  "GetBowAndArrowSlot",   "弓矢スロット取得"),
            new ESDFunction(357,  "GetWeaponStorageSpotType",   "武器格納場所タイプ取得"),
            new ESDFunction(358,  "GetStayAnimCategory",   "待機アニメカテゴリ取得"),
            new ESDFunction(359,  "GetWeaponSwitchStatus",   "Obtain Weapon Switching Status"),
            new ESDFunction(360,  "IsEquipmentMenuOpen",   "装備メニュー開いているか"),
            new ESDFunction(361,  "GetRemainingArrowCount",   "矢の残弾数取得"),
            new ESDFunction(362,  "GetSpEffectType",   "362"),
            new ESDFunction(363,  "Unknown363",   "363"),
            new ESDFunction(364,  "GetEventID",   "364"),
            new ESDFunction(365,  "Unknown365",   "365"),
            new ESDFunction(366,  "GetSpiritspringJumpHeight",   "366"),
            new ESDFunction(368,  "Unknown368",   "368"),

            new ESDFunction(400,  "GetPoise",   "400"),
            new ESDFunction(402,  "GetMaxPoise",   "402"),
            new ESDFunction(403,  "GetSpEffectEventAnimID",   "403"),
            new ESDFunction(404,  "Unknown404",   "404"),
            new ESDFunction(405,  "Unknown405",   "405"),
            new ESDFunction(406,  "GetRollAngle",   "406"),
            new ESDFunction(407,  "GetJumpAngle",   "407"),
            new ESDFunction(408,  "GetSwordArtsRollAngle",   "408"),
            new ESDFunction(409,  "GetDamageSpecialAttribute",   "409"),

            new ESDFunction(500,  "IsOnMount",   "500"),
            new ESDFunction(502,  "Unknown502",   "502"),
            new ESDFunction(504,  "IsSummoningRide",   "504"),
            new ESDFunction(505,  "IsMovingOnMount",   "505"),
            new ESDFunction(506,  "IsIdleOnMount",   "506"),
            new ESDFunction(522,  "GetMountReceivedDamageDirection",   "522"),
            new ESDFunction(530,  "GetMountDamageLevel",   "530"),
            new ESDFunction(533,  "GetMountRecievedDamageAngle",   "533"),
            new ESDFunction(534,  "GetMountRecievedDamageType",   "534"),
            new ESDFunction(535,  "HasMountReceivedAnyDamage",   "535"),
            new ESDFunction(537,  "IsMountFalling",   "537"),
            new ESDFunction(538,  "GetMountFallHeight",   "538"),
            new ESDFunction(539,  "IsMountInFallLoop",   "539"),
            new ESDFunction(540,  "IsMountTrulyLanding",   "540"),
            new ESDFunction(543,  "GetMountSpecialAttribute",   "543"),
            new ESDFunction(545,  "IsMountDead",   "545"),
            new ESDFunction(546,  "GetMountIsWeakPoint",   "546"),
            new ESDFunction(547,  "GetMountDamageAnimID",   "547"),
            new ESDFunction(548,  "Unknown548",   "548"),
            new ESDFunction(549,  "GetMountSpEffectID",   "549"),
            new ESDFunction(550,  "GetMountSpEffectType",   "550"),
            new ESDFunction(551,  "GetMountStateInfo",   "551"),
            new ESDFunction(552,  "Unknown552",   "552"),
            new ESDFunction(553,  "GetMountBehaviorID",   "553"),
            new ESDFunction(554,  "GetMountStatusEffect",   "554"),
            new ESDFunction(555,  "Unknown555",   "555"),

            new ESDFunction(600,  "GetFlyRouteState",   "600"),

            new ESDFunction(700,  "Unknown700",   "700"),
            new ESDFunction(701,  "Unknown701",   "701"),

            new ESDFunction(1000, "GetHP",   "HP取得"),
            new ESDFunction(1001, "GetStamina",   "スタミナ取得"),
            new ESDFunction(1002, "IsGhost",   "ゴーストか"),
            new ESDFunction(1003, "GetRandomInt",   "整数ランダム値取得"),
            new ESDFunction(1004, "GetRandomFloat",   "小数ランダム値取得"),
            new ESDFunction(1005, "IsUnableToDie",   "成仏不可か"),
            new ESDFunction(1006, "IsResurrectionPossible",   "蘇生可能か"),
            new ESDFunction(1007, "IsCOMPlayer",   "COMプレイヤか"),
            new ESDFunction(1008, "GetAITargetAwareState",   "AIのターゲット認識状態取得"),
            new ESDFunction(1009, "IsAIChangeToAwareState",   "AI認識状態に変化あるか"),
            new ESDFunction(1010, "GetAITargetAwareStatePreviousFrame",   "前のフレームのAIターゲット認識状態取得"),

            new ESDFunction(1100, "GetTestDamageAnimID",   "テスト用ダメージアニメID取得"),
            new ESDFunction(1101, "IsInvincibleDebugMode",   "無敵デバッグモード有効か"),
            new ESDFunction(1102, "WasGameLaunchedInPGTestMode",   "PGテストモード起動しているか"),
            new ESDFunction(1103, "IsTiltingStick",   "スティックを傾けたか"),
            new ESDFunction(1104, "GetGestureRequestNumber",   "ジェスチャーリクエスト番号を取得"),
            new ESDFunction(1105, "IsStayState",   "待機ステートか"),
            new ESDFunction(1106, "ActionRequest",   "アクションリクエスト"),
            new ESDFunction(1107, "ActionCancelRequest",   "アクション解除リクエスト"),
            new ESDFunction(1108, "ActionDuration",   "アクション継続時間"),
            new ESDFunction(1109, "HasActionRequest",   "何かアクションリクエストがあるか"),
            new ESDFunction(1110, "MovementRequest",   "移動リクエスト"),
            new ESDFunction(1111, "MovementRequestDuration",   "移動リクエスト継続時間"),
            new ESDFunction(1112, "HasThrowRequest",   "投げ要求か"),
            new ESDFunction(1113, "IsGuardCancelPossible",   "ガードキャンセル可能か"),
            new ESDFunction(1114, "DoesAnimExist",   "アニメが存在するか"),
            new ESDFunction(1115, "GetAIMovementType",   "AI移動タイプ取得"),
            new ESDFunction(1116, "GetSpEffectID",   "特殊効果IDを取得"),
            new ESDFunction(1117, "IsConversationEnd",   "会話が終了したか"),
            new ESDFunction(1118, "IsLocked",   "ロック中か"),
            new ESDFunction(1119, "GetAtkDirection",   "攻撃方向取得"),
            new ESDFunction(1120, "GetPartGroup",   "部位グループ取得"),
            new ESDFunction(1121, "GetKnockbackDistance",   "ノックバック距離取得"),

            new ESDFunction(2000, "IsMoveCancelPossible",   "移動キャンセル可能か"),
            new ESDFunction(2002, "GetSpecialMovementType",   "特殊移動タイプ取得"),
            new ESDFunction(2003, "GetGeneralTAEFlag",   "TAE汎用フラグ取得"),
            new ESDFunction(2004, "IsSwingHitTarget",   "振りが当たっているか"),
            new ESDFunction(2005, "GetCeremonyState",   "儀式状態を取得"),
            new ESDFunction(2006, "GetSuccessiveGuardCount",   "連続ガード回数を取得"),
            new ESDFunction(2007, "GetMinLuck",   "最小よろけ値を取得"),
            new ESDFunction(2008, "GetAccumulatedLuck",   "蓄積よろけ値を取得"),
            new ESDFunction(2009, "GetMaxLuck",   "最大よろけ値を取得"),
            new ESDFunction(2010, "GetMaxStamina",   "最大スタミナ取得"),
            new ESDFunction(2011, "GetGeneralMSBParameter",   "MSB汎用パラメータ取得"),
            new ESDFunction(2012, "IsHitWall",   "壁に当たっているか"),
            new ESDFunction(2013, "GetSafetyDirection",   "安全方向取得"),
            new ESDFunction(2014, "IsInCeremony",   "儀式中か"),
            new ESDFunction(2015, "IsDoingCorpseCarryKeyframe",   "死体運びキーフレーム化するか"),
            new ESDFunction(2016, "GetFP",   "MP取得"),
            new ESDFunction(2017, "IsCeremonyComplete",   "儀式完了か"),
            new ESDFunction(2018, "IsCeremonyInterrupt",   "儀式中断か"),

            new ESDFunction(3000, "IsSpeaking",   "3000"),
            new ESDFunction(3001, "GetTalkID_3001",   "3001"),
            new ESDFunction(3002, "GetTalkID_3002",   "3002")
        };

        public static ESDFunction[] ESDActs = new ESDFunction[]
        {
            new ESDFunction(0, "ChangeGeneralAnim", "0"),
            new ESDFunction(1, "ChangeUpperBodyAnim", "1"),
            new ESDFunction(2, "ChangeStayAnim", "2"),
            new ESDFunction(3, "ChangeGeneralAnimCategorized", "3"),
            new ESDFunction(4, "ChangeUpperBodyAnimCategorized", "4"),
            new ESDFunction(5, "ChangeGeneralAnimAdditiveCategorized", "5"),
            new ESDFunction(6, "ChangeUpperBodyAnimAdditiveCategorized", "6"),
            new ESDFunction(7, "ChangeGeneralAnimCategorizedMatchPlaybackTime", "7"),
            new ESDFunction(8, "ChangeUpperBodyAnimCategorizedMatchPlaybackTime", "8"),
            new ESDFunction(9, "SetAnimIDOffset", "9"),
            new ESDFunction(10, "SetAdditiveBlendAnimation", "10"),
            new ESDFunction(11, "SetAdditiveBlendAnimationSlotted", "11"),
            new ESDFunction(12, "ChangeBlendAnimationCategorized", "12"),
            new ESDFunction(13, "ChangeUpperAndLowerBodySyncedAnimCategorized", "13"),

            new ESDFunction(100, "SetActiveActionState", "100"),
            new ESDFunction(101, "SwitchMotion", "101"),
            new ESDFunction(102, "SetAllowedThrowAttackType", "102"),
            new ESDFunction(103, "SetAllowedThrowDefenseType", "103"),
            new ESDFunction(104, "SwitchEquippedWeapon", "104"),
            new ESDFunction(105, "SetReadyForAtkFinish", "105"),
            new ESDFunction(106, "SetEquipmentChangeable", "106"),
            new ESDFunction(107, "SetUnableToFall", "107"),
            new ESDFunction(108, "SendMessageIDToEvents", "108"),
            new ESDFunction(109, "SetAttackType", "109"),
            new ESDFunction(110, "SetStaminaRecoveryDisabled", "110"),
            new ESDFunction(111, "SetAIBusyDoingAction", "111"),
            new ESDFunction(112, "BowTurn", "112"),
            new ESDFunction(113, "SetBowStance", "113"),
            new ESDFunction(114, "SetPreciseAimMode", "114"),
            new ESDFunction(115, "SetSpecialMovement", "115"),
            new ESDFunction(116, "SetIsWeaponChanging", "116"),
            new ESDFunction(117, "SetIsItemInUse", "117"),
            new ESDFunction(118, "SetIsMagicInUse", "118"),
            new ESDFunction(119, "SetHoverState", "119"),
            new ESDFunction(120, "RemoveBinoculars", "120"),
            new ESDFunction(121, "ChangeToSpecialStay", "121"),
            new ESDFunction(122, "SetIsHeadTurnPossible", "122"),
            new ESDFunction(123, "OpenMenuWhenUsingItem", "123"),
            new ESDFunction(124, "OpenMenuWhenUsingMagic", "124"),
            new ESDFunction(125, "BlowDamageTurn", "125"),
            new ESDFunction(126, "SetDeathStay", "126"),
            new ESDFunction(127, "CloseMenuWhenUsingItem", "127"),
            new ESDFunction(128, "CloseMenuWhenUsingMagic", "128"),
            new ESDFunction(129, "DisallowAdditiveTurning", "129"),
            new ESDFunction(130, "ChangeFlightStatus", "130"),
            new ESDFunction(131, "ShowFixedYAxisDirectionDisplay", "131"),
            new ESDFunction(132, "WhiffPossibility", "132"),
            new ESDFunction(133, "SetLadderActionState", "133"),
            new ESDFunction(134, "SetInsufficientStrengthAnimID", "134"),
            new ESDFunction(135, "ForceCancelThrowAnim", "135"),
            new ESDFunction(136, "SetThrowState", "136"),
            new ESDFunction(137, "StartSlidingDownLadder", "137"),
            new ESDFunction(138, "SetIsEventActionPossible", "138"),
            new ESDFunction(139, "RequestThrowAnimInterrupt", "139"),
            new ESDFunction(140, "SetHandStateOfLadder", "140"),
            new ESDFunction(141, "SetDamageAnimType", "141"),
            new ESDFunction(142, "DownwardSlideTurn", "142"),
            new ESDFunction(143, "InterruptAttack", "143"),
            new ESDFunction(144, "SkyDeathWarp", "144"),
            new ESDFunction(145, "ClearSlopeInfo", "145"),
            new ESDFunction(146, "ReceiveStateInput", "146"),
            new ESDFunction(147, "SetIsEquipmentChangeableFromMenu", "147"),
            new ESDFunction(148, "SetHavokVariable", "148"),
            new ESDFunction(149, "AimAtSelfPosition", "149"),
            new ESDFunction(150, "SetIsItemAnimationPlaying", "150"),
            new ESDFunction(151, "DoAIReplanningAtCancelTiming", "151"),
            new ESDFunction(152, "DenyEventAnimPlaybackRequest", "152"),
            new ESDFunction(153, "InvokeBackstab", "153"),
            new ESDFunction(154, "WeaponParameterReference", "154"),
            new ESDFunction(155, "AINotifyAttackType", "155"),
            new ESDFunction(156, "SetAutoCaptureTarget", "156"),
            new ESDFunction(157, "ClearAutoCaptureTarget", "157"),
            new ESDFunction(158, "RequestAIReplanning", "158"),
            new ESDFunction(159, "TurnTowardAttacker", "159"),
            new ESDFunction(160, "SetThrowPossibilityState_Attacker", "160"),
            new ESDFunction(161, "SetThrowPossibilityState_Defender", "161"),
            new ESDFunction(162, "MarkOfGreedyPersonSlipDamageDisable", "162"),
            new ESDFunction(163, "Unknown163", "163"),

            new ESDFunction(200, "StateIdentifier", "200"),

            new ESDFunction(1000, "ChangeHP", "1000"),
            new ESDFunction(1001, "ChangeStamina", "1001"),
            new ESDFunction(1100, "SyncAtInit_Active", "1100"),
            new ESDFunction(1101, "SyncAtInit_Passive", "1101"),

            new ESDFunction(2001, "SetMovementScaleMult", "2001"),
            new ESDFunction(2002, "AddSpEffect", "2002"),
            new ESDFunction(2003, "SetFastStealthThrowEnabled", "2003"),
            new ESDFunction(2004, "SetTurnSpeed", "2004"),
            new ESDFunction(2005, "SetCeremonyState", "2005"),
            new ESDFunction(2006, "SetDamageMotionBlendRatio", "2006"),
            new ESDFunction(2007, "SetForceTurnTarget", "2007"),
            new ESDFunction(2008, "ForceTurn", "2008"),
            new ESDFunction(2009, "SpecialTurn", "2009"),
            new ESDFunction(2010, "SetInSpecialGuard", "2010"),
            new ESDFunction(2011, "SetWeaponCancelType", "2011"),
            new ESDFunction(2012, "SetIsPreciseShootingPossible", "2012"),
            new ESDFunction(2013, "ChooseBowAndArrowSlot", "2013"),
            new ESDFunction(2014, "Set4DirectionMovementThreshold", "2014"),
            new ESDFunction(2015, "LockonSystemUnableToTurnAngle", "2015"),
            new ESDFunction(2016, "ReserveArtsPointsUse", "2016"),
            new ESDFunction(2017, "SetArtsPointFEDisplayState", "2017"),
            new ESDFunction(2018, "LockonFixedAngleCancel", "2018"),
            new ESDFunction(2019, "TurnToLockonTargetImmediately", "2019"),
            new ESDFunction(2020, "SetSpecialInterpolation", "2020"),
            new ESDFunction(2021, "LadderSlideDownCancel", "2021"),
            new ESDFunction(2022, "DisableMagicIDSwitching", "2022"),
            new ESDFunction(2023, "DisableToolIDSwitching", "2023"),
            new ESDFunction(2024, "UseItemDecision", "2024"),
            new ESDFunction(2025, "Unknown2025", "2025"),
            new ESDFunction(2026, "Unknown2026", "2026"),
            new ESDFunction(2027, "Unknown2027", "2027"),
            new ESDFunction(2029, "Unknown2029", "2029"),
            new ESDFunction(2030, "ChangeBuddyState", "2030"),
            new ESDFunction(2031, "PlayEventSync", "2031"),
            new ESDFunction(2040, "Unknown2040", "2040"),
            new ESDFunction(2050, "Unknown2050", "2050"),

            new ESDFunction(3000, "Unknown3000", "3000"),
            new ESDFunction(3001, "Unknown3001", "3001"),
            new ESDFunction(3002, "Unknown3002", "3002"),
            new ESDFunction(3003, "PlayRideAnim", "3003"),
            new ESDFunction(3004, "ApplyRideBlend", "3004"),
            new ESDFunction(3005, "Unknown3005", "3005"),
            new ESDFunction(3006, "Unknown3006", "3006"),
            new ESDFunction(3007, "ApplyDamageFlag", "3007"),

            new ESDFunction(4000, "Unknown4000", "4000"),
            new ESDFunction(4001, "Unknown4001", "4001"),
            new ESDFunction(4002, "Unknown4002", "4002"),

            new ESDFunction(9000, "DebugLogOutput", "9000"),
            new ESDFunction(9001, "Test_SpEffectDelete", "9001"),
            new ESDFunction(9002, "Test_SpEffectTypeSpecifyDelete", "9002"),
            new ESDFunction(9003, "MarkerStart", "9003"),
            new ESDFunction(9004, "MarkerEnd", "9004"),

            new ESDFunction(9100, "Wait", "9100"),
            new ESDFunction(9101, "ResetInputQueue", "9101"),
            new ESDFunction(9102, "SetIsEventAnim", "9102"),
            new ESDFunction(9103, "SetAIAttackState", "9103"),
            new ESDFunction(9104, "SetIsTurnAnimInProgress", "9104"),
            new ESDFunction(9105, "SetTurnAnimCorrectionRate", "9105"),

            new ESDFunction(9999, "Unknown9999", "9999")
        };
    }
}
